[project]
name = "pm-rs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas>=3.0.0",
]

[dependency-groups]
dev = [
    "ipykernel>=7.1.0",
    "ipython>=9.10.0",
    "ipywidgets>=8.1.8",
    "seaborn>=0.13.2",
]
